/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Wellcome;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Gulam Kibria
 */
public class About_Developer extends javax.swing.JFrame {

    /**
     * Creates new form About_Developer
     */
    private Container c;
    private ImageIcon im1,im2,im3,im4,im5,im6,im7,im8;
    
    public About_Developer() {
        initComponents();
        c = this.getContentPane();
        this.setVisible(true);
        this.setSize(957,697);
        this.setLocation(260, 2);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("About_Developer");
        this.setResizable(false);
        c.setBackground(Color.PINK);
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Gulam_Kibria.png")));
        Image im1 = myimage.getImage();
        Image im2 = im1.getScaledInstance(Kibria_label.getWidth(),Kibria_label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ff=new ImageIcon(im2);
        Kibria_label.setIcon(ff);
        ImageIcon myimage1=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Reza.png")));
        Image im3 = myimage1.getImage();
        Image im4 = im3.getScaledInstance(Raza_lebel.getWidth(),Raza_lebel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ff1=new ImageIcon(im4);
        Raza_lebel.setIcon(ff1);
        ImageIcon myimage2=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Tania.png")));
        Image im5 = myimage2.getImage();
        Image im6 = im5.getScaledInstance(Tania_lebel.getWidth(),Tania_lebel.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ff2=new ImageIcon(im6);
        Tania_lebel.setIcon(ff2);
        ImageIcon myimage3=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Sojib_sir.png")));
        Image im7 = myimage3.getImage();
        Image im8 = im7.getScaledInstance(Sojib_label.getWidth(),Sojib_label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ff3=new ImageIcon(im8);
        Sojib_label.setIcon(ff3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sojib_Panel = new javax.swing.JPanel();
        Sojib_label = new javax.swing.JLabel();
        Raza_Panel = new javax.swing.JPanel();
        Raza_lebel = new javax.swing.JLabel();
        Kibria_Panel = new javax.swing.JPanel();
        Kibria_label = new javax.swing.JLabel();
        Tanai_Panel = new javax.swing.JPanel();
        Tania_lebel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        sojib_sir_area1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        sojib_sir_area2 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        sojib_sir_area3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        sojib_sir_area4 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        Sojib_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sojib_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));

        javax.swing.GroupLayout Sojib_PanelLayout = new javax.swing.GroupLayout(Sojib_Panel);
        Sojib_Panel.setLayout(Sojib_PanelLayout);
        Sojib_PanelLayout.setHorizontalGroup(
            Sojib_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
            .addGroup(Sojib_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Sojib_label, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );
        Sojib_PanelLayout.setVerticalGroup(
            Sojib_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(Sojib_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Sojib_label, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );

        getContentPane().add(Sojib_Panel);
        Sojib_Panel.setBounds(17, 11, 339, 220);

        Raza_lebel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Raza_lebel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));

        javax.swing.GroupLayout Raza_PanelLayout = new javax.swing.GroupLayout(Raza_Panel);
        Raza_Panel.setLayout(Raza_PanelLayout);
        Raza_PanelLayout.setHorizontalGroup(
            Raza_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
            .addGroup(Raza_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Raza_lebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
        Raza_PanelLayout.setVerticalGroup(
            Raza_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
            .addGroup(Raza_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Raza_lebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        getContentPane().add(Raza_Panel);
        Raza_Panel.setBounds(27, 277, 234, 174);

        Kibria_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Kibria_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));

        javax.swing.GroupLayout Kibria_PanelLayout = new javax.swing.GroupLayout(Kibria_Panel);
        Kibria_Panel.setLayout(Kibria_PanelLayout);
        Kibria_PanelLayout.setHorizontalGroup(
            Kibria_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
            .addGroup(Kibria_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Kibria_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
        Kibria_PanelLayout.setVerticalGroup(
            Kibria_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
            .addGroup(Kibria_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Kibria_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        getContentPane().add(Kibria_Panel);
        Kibria_Panel.setBounds(377, 277, 234, 174);

        Tania_lebel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tania_lebel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));

        javax.swing.GroupLayout Tanai_PanelLayout = new javax.swing.GroupLayout(Tanai_Panel);
        Tanai_Panel.setLayout(Tanai_PanelLayout);
        Tanai_PanelLayout.setHorizontalGroup(
            Tanai_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
            .addGroup(Tanai_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tania_lebel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
        );
        Tanai_PanelLayout.setVerticalGroup(
            Tanai_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 174, Short.MAX_VALUE)
            .addGroup(Tanai_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Tania_lebel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
        );

        getContentPane().add(Tanai_Panel);
        Tanai_Panel.setBounds(710, 277, 234, 174);

        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(17, 249, 930, 10);

        sojib_sir_area1.setEditable(false);
        sojib_sir_area1.setColumns(20);
        sojib_sir_area1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        sojib_sir_area1.setForeground(new java.awt.Color(51, 0, 51));
        sojib_sir_area1.setLineWrap(true);
        sojib_sir_area1.setRows(5);
        sojib_sir_area1.setText("                               Supervised By:\n\n                               Noushad Sojib\n                         Lecturer,dept. of CSE.\n              North East University Bangladesh");
        sojib_sir_area1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));
        jScrollPane2.setViewportView(sojib_sir_area1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(413, 11, 534, 220);

        sojib_sir_area2.setEditable(false);
        sojib_sir_area2.setColumns(20);
        sojib_sir_area2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sojib_sir_area2.setRows(5);
        sojib_sir_area2.setText("              Developed By :\n        Tania Sultana Mou\n        Reg No:170103020005\n        Semester: 6th\n        Section: A\n        Mobile No: 01788-518699\n        Email Id: tania.neub@gmail.com");
        sojib_sir_area2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));
        jScrollPane4.setViewportView(sojib_sir_area2);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(671, 482, 273, 180);

        sojib_sir_area3.setEditable(false);
        sojib_sir_area3.setColumns(20);
        sojib_sir_area3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sojib_sir_area3.setRows(5);
        sojib_sir_area3.setText("               Developed By :\n      Gulam Kibria Chowdhury\n      Reg No:170103020033\n      Semester: 6th\n      Section: A\n      Mobile No: 01718-389885\n      Email Id: gkpalash101@gmail.com");
        sojib_sir_area3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));
        jScrollPane5.setViewportView(sojib_sir_area3);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(348, 482, 292, 180);

        sojib_sir_area4.setEditable(false);
        sojib_sir_area4.setColumns(20);
        sojib_sir_area4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sojib_sir_area4.setRows(5);
        sojib_sir_area4.setText("                Developed By :\n          Kutub Uddin(Reza)\n          Reg No:170103020047\n          Semester: 6th\n          Section: A\n          Mobile No: 01765-744899\n         Email Id: rezaneub06@gmail.com");
        sojib_sir_area4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 5, true));
        jScrollPane6.setViewportView(sojib_sir_area4);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(10, 482, 286, 180);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 500, 460);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 450, 500, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 450, 460, 240);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(500, -6, 460, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_Developer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_Developer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Kibria_Panel;
    private javax.swing.JLabel Kibria_label;
    private javax.swing.JPanel Raza_Panel;
    private javax.swing.JLabel Raza_lebel;
    private javax.swing.JPanel Sojib_Panel;
    private javax.swing.JLabel Sojib_label;
    private javax.swing.JPanel Tanai_Panel;
    private javax.swing.JLabel Tania_lebel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea sojib_sir_area1;
    private javax.swing.JTextArea sojib_sir_area2;
    private javax.swing.JTextArea sojib_sir_area3;
    private javax.swing.JTextArea sojib_sir_area4;
    // End of variables declaration//GEN-END:variables
}
