/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Wellcome;

import com.sun.xml.internal.ws.api.server.Container;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Gulam Kibria
 */
public class About_Project extends javax.swing.JFrame {

    /**
     * Creates new form About_Project
     */
    private JMenu m1, m2, m3;
    private JMenuBar mm;
    private JMenuItem b1, b2, b3, b4, b5;
    private java.awt.Container c;

    public About_Project() {
        initComponents();
        c = this.getContentPane();
        this.setVisible(true);
        this.setSize(841,548);
        this.setLocation(280, 102);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("About_Project");
        this.setResizable(false);
        c.setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        About_Project = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        About_Project.setEditable(false);
        About_Project.setBackground(new java.awt.Color(204, 255, 204));
        About_Project.setColumns(20);
        About_Project.setFont(new java.awt.Font("SolaimanLipi", 3, 24)); // NOI18N
        About_Project.setRows(5);
        About_Project.setText("বাংলা ইভেন্ট ক্যালেন্ডার প্রজেক্টি একটি অভিনব প্রজেক্ট।এই প্রজেক্টের মাধ্যমে আমরা\nবাংলাদেশের ইতিহাস,ঐতিহ্য - মণ্ডিত দিনগুলো সম্পর্কে,বিভিন্ন নৃ - তত্ত্য জনগোস্টীর \nবিভিন্ন উৎসব সম্পর্কে  জানতে পারব । বিশেষ দিনটি কবে থেকে উদযাপন হচ্ছে তাঁর \nতারিখ , বাংলা  তারিখ  এবং দিনটি  কি বার তা জানা যায়। আন্তর্জাতিক বিভিন্ন দিবস \nসম্পর্কে  বিসদভাবে  জানা যায় । বিভিন্ন  দেশ থেকে  আগত  বাংলা  জানা শিল্পী ও \nঅতিথিগণ এই প্রজেক্টের মাধ্যমে আমাদের দেশের সংস্কৃতি সম্পর্কে খুব সহজে অবগত \nহতে পারবেন । এর মাধ্যমে  আমরা অনেক  উৎসবের ইতিহাস এর উৎস ,ব্যাপ্তিকাল \nএবং  উৎসব পালনের  নিয়ম খুব  সহজেই  জানতে পারি । যে কেউ  চাইলে নিজের \nপছন্দমত দিনটি আমাদের ইভেন্টে ক্যালেন্ডারে যোগ করতে পারেন। ");
        About_Project.setToolTipText("About_Project");
        About_Project.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        jScrollPane2.setViewportView(About_Project);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 11, 821, 513);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, -6, 860, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About_Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About_Project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea About_Project;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
