/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Wellcome;

import java.awt.Color;
import java.awt.Container;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kibria
 */
public class AddEvent extends javax.swing.JFrame {

    /**
     * Creates new form AddEvent
     */
    private Container c;
    DefaultTableModel model;
    int x = 0, dd = 00, mm = 00, yy = 00;
    String allDate = "", dateday, day = "", month = "", year = "", EventName1, AllDate1;

    public AddEvent() {
        initComponents();
        c = this.getContentPane();
        Current_Date_Time ff = new Current_Date_Time();
        String Time = ff.Current_Time;
        String Date = ff.Current_Date;
        Current_time2.setText(Time);
        Current_date2.setText(Date);
        
        this.setVisible(true);
        this.setSize(1318,776);
        this.setLocation(10, 15);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //Jdate1.setDate(ff.date);
        this.setTitle("Smart_Calender");
        this.setResizable(false);
        c.setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DataEntryDMY = new javax.swing.JLabel();
        AllDataTextButton = new javax.swing.JButton();
        AddEventLavel = new javax.swing.JLabel();
        AddEventFieldEventName = new javax.swing.JTextField();
        AddEventClear2 = new javax.swing.JButton();
        INFOLavel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        AllDateText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddTextArea = new javax.swing.JTextArea();
        AddClearButton = new javax.swing.JButton();
        AddEnterButton = new javax.swing.JButton();
        AddBackButton = new javax.swing.JButton();
        AddInformationLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ChooseEventFieldname = new javax.swing.JTextField();
        ChooseEventFieldDate = new javax.swing.JTextField();
        ChooseEventEnterButton = new javax.swing.JButton();
        ChooseExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AddEventTabel = new javax.swing.JTable();
        ChooseEventLabel = new javax.swing.JLabel();
        jb4 = new javax.swing.JButton();
        Current_date2 = new javax.swing.JTextField();
        jb10 = new javax.swing.JButton();
        Time_date = new javax.swing.JTextField();
        Current_Date2 = new javax.swing.JLabel();
        jb3 = new javax.swing.JButton();
        Current_Time2 = new javax.swing.JLabel();
        jb5 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        Current_time2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DataEntryDMY.setBackground(new java.awt.Color(153, 153, 255));
        DataEntryDMY.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        DataEntryDMY.setText("     dd/mm/yy");
        DataEntryDMY.setToolTipText("");
        DataEntryDMY.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 0), 4, true));
        getContentPane().add(DataEntryDMY);
        DataEntryDMY.setBounds(500, 200, 160, 41);

        AllDataTextButton.setBackground(new java.awt.Color(51, 0, 51));
        AllDataTextButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AllDataTextButton.setForeground(new java.awt.Color(204, 255, 0));
        AllDataTextButton.setText("OK");
        AllDataTextButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AllDataTextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AllDataTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDataTextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AllDataTextButton);
        AllDataTextButton.setBounds(335, 234, 79, 55);

        AddEventLavel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AddEventLavel.setForeground(new java.awt.Color(51, 0, 51));
        AddEventLavel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddEventLavel.setText("Please add your Date,Event Name  & Information");
        AddEventLavel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 0), 12, true));
        getContentPane().add(AddEventLavel);
        AddEventLavel.setBounds(20, 127, 650, 60);

        AddEventFieldEventName.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddEventFieldEventName.setForeground(new java.awt.Color(51, 0, 51));
        AddEventFieldEventName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        getContentPane().add(AddEventFieldEventName);
        AddEventFieldEventName.setBounds(139, 352, 451, 52);

        AddEventClear2.setBackground(new java.awt.Color(51, 0, 51));
        AddEventClear2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddEventClear2.setForeground(new java.awt.Color(0, 102, 102));
        AddEventClear2.setText("Clear");
        AddEventClear2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEventClear2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEventClear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventClear2ActionPerformed(evt);
            }
        });
        getContentPane().add(AddEventClear2);
        AddEventClear2.setBounds(608, 359, 77, 39);

        INFOLavel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        INFOLavel.setForeground(new java.awt.Color(51, 0, 51));
        INFOLavel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        INFOLavel.setText("Add your Information");
        INFOLavel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        getContentPane().add(INFOLavel);
        INFOLavel.setBounds(191, 415, 336, 33);

        jSeparator1.setBackground(new java.awt.Color(51, 0, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 2, true));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 339, 670, 2);

        AllDateText.setEditable(false);
        AllDateText.setBackground(new java.awt.Color(153, 153, 255));
        AllDateText.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AllDateText.setForeground(new java.awt.Color(51, 0, 51));
        AllDateText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AllDateText.setToolTipText("Date");
        AllDateText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 5, true));
        AllDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDateTextActionPerformed(evt);
            }
        });
        getContentPane().add(AllDateText);
        AllDateText.setBounds(481, 252, 199, 60);

        AddTextArea.setBackground(new java.awt.Color(204, 204, 204));
        AddTextArea.setColumns(20);
        AddTextArea.setFont(new java.awt.Font("SolaimanLipi", 3, 18)); // NOI18N
        AddTextArea.setForeground(new java.awt.Color(51, 0, 51));
        AddTextArea.setRows(5);
        AddTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jScrollPane1.setViewportView(AddTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 459, 670, 158);

        AddClearButton.setBackground(new java.awt.Color(51, 0, 51));
        AddClearButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddClearButton.setForeground(new java.awt.Color(0, 102, 102));
        AddClearButton.setText("Clear");
        AddClearButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddClearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddClearButton);
        AddClearButton.setBounds(296, 635, 117, 31);

        AddEnterButton.setBackground(new java.awt.Color(51, 0, 51));
        AddEnterButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddEnterButton.setForeground(new java.awt.Color(0, 102, 102));
        AddEnterButton.setText("Add");
        AddEnterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEnterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEnterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddEnterButton);
        AddEnterButton.setBounds(453, 635, 117, 31);

        AddBackButton.setBackground(new java.awt.Color(51, 0, 51));
        AddBackButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddBackButton.setForeground(new java.awt.Color(0, 102, 102));
        AddBackButton.setText("Home");
        AddBackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddBackButton);
        AddBackButton.setBounds(139, 635, 116, 31);

        AddInformationLabel.setBackground(new java.awt.Color(153, 153, 153));
        AddInformationLabel.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddInformationLabel.setForeground(new java.awt.Color(51, 51, 0));
        AddInformationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddInformationLabel.setText("Event Name :");
        AddInformationLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        getContentPane().add(AddInformationLabel);
        AddInformationLabel.setBounds(10, 352, 119, 52);

        jSeparator4.setBackground(new java.awt.Color(102, 0, 102));
        jSeparator4.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 1, true));
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(463, 193, 8, 135);

        jSeparator2.setForeground(new java.awt.Color(51, 0, 51));
        jSeparator2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(711, 0, 9, 666);

        ChooseEventFieldname.setEditable(false);
        ChooseEventFieldname.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseEventFieldname.setForeground(new java.awt.Color(51, 0, 51));
        ChooseEventFieldname.setToolTipText("Event Name");
        ChooseEventFieldname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 2, true));
        getContentPane().add(ChooseEventFieldname);
        ChooseEventFieldname.setBounds(731, 11, 329, 56);

        ChooseEventFieldDate.setEditable(false);
        ChooseEventFieldDate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseEventFieldDate.setForeground(new java.awt.Color(51, 0, 51));
        ChooseEventFieldDate.setToolTipText("Date");
        ChooseEventFieldDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 2, true));
        getContentPane().add(ChooseEventFieldDate);
        ChooseEventFieldDate.setBounds(1096, 13, 107, 53);

        ChooseEventEnterButton.setBackground(new java.awt.Color(51, 0, 51));
        ChooseEventEnterButton.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseEventEnterButton.setForeground(new java.awt.Color(0, 204, 204));
        ChooseEventEnterButton.setText("Enter");
        ChooseEventEnterButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChooseEventEnterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseEventEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseEventEnterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseEventEnterButton);
        ChooseEventEnterButton.setBounds(1221, 26, 68, 27);

        ChooseExit.setBackground(new java.awt.Color(51, 0, 51));
        ChooseExit.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseExit.setForeground(new java.awt.Color(0, 204, 204));
        ChooseExit.setText("Exit");
        ChooseExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ChooseExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseExitActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseExit);
        ChooseExit.setBounds(976, 639, 108, 27);

        AddEventTabel.setBackground(new java.awt.Color(204, 204, 204));
        AddEventTabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        AddEventTabel.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        AddEventTabel.setForeground(new java.awt.Color(51, 0, 51));
        AddEventTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "                 NO", "               Event  ", "                    Date  "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AddEventTabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEventTabel.setRowHeight(25);
        AddEventTabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddEventTabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AddEventTabel);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(731, 135, 558, 463);

        ChooseEventLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ChooseEventLabel.setForeground(new java.awt.Color(51, 0, 51));
        ChooseEventLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ChooseEventLabel.setText(" Event List");
        ChooseEventLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 2, true));
        getContentPane().add(ChooseEventLabel);
        ChooseEventLabel.setBounds(961, 85, 133, 32);

        jb4.setBackground(new java.awt.Color(153, 255, 204));
        jb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jb4);
        jb4.setBounds(395, 36, 23, 18);

        Current_date2.setEditable(false);
        Current_date2.setBackground(new java.awt.Color(204, 204, 204));
        Current_date2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_date2.setForeground(new java.awt.Color(51, 51, 51));
        Current_date2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Current_date2.setToolTipText("Current_Date");
        Current_date2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Current_date2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Current_date2ActionPerformed(evt);
            }
        });
        getContentPane().add(Current_date2);
        Current_date2.setBounds(486, 61, 207, 48);

        jb10.setBackground(new java.awt.Color(153, 255, 204));
        jb10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb10ActionPerformed(evt);
            }
        });
        getContentPane().add(jb10);
        jb10.setBounds(437, 78, 23, 18);

        Time_date.setEditable(false);
        Time_date.setBackground(new java.awt.Color(204, 102, 0));
        Time_date.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Time_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Time_date.setToolTipText("");
        Time_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        Time_date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Time_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_dateActionPerformed(evt);
            }
        });
        getContentPane().add(Time_date);
        Time_date.setBounds(214, 61, 254, 11);

        Current_Date2.setBackground(new java.awt.Color(204, 204, 204));
        Current_Date2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_Date2.setForeground(new java.awt.Color(0, 51, 51));
        Current_Date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Current_Date2.setText("Current_Date");
        Current_Date2.setToolTipText("Current_Date");
        Current_Date2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        getContentPane().add(Current_Date2);
        Current_Date2.setBounds(488, 9, 205, 45);

        jb3.setBackground(new java.awt.Color(51, 0, 51));
        jb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb3);
        jb3.setBounds(337, 36, 23, 19);

        Current_Time2.setBackground(new java.awt.Color(204, 204, 204));
        Current_Time2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_Time2.setForeground(new java.awt.Color(0, 51, 51));
        Current_Time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Current_Time2.setText("Current_Time");
        Current_Time2.setToolTipText("Current_Time");
        Current_Time2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        getContentPane().add(Current_Time2);
        Current_Time2.setBounds(0, 10, 208, 45);

        jb5.setBackground(new java.awt.Color(51, 0, 51));
        jb5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb5);
        jb5.setBounds(439, 37, 23, 18);

        jb1.setBackground(new java.awt.Color(51, 0, 51));
        jb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb1);
        jb1.setBounds(228, 36, 23, 18);

        jb6.setBackground(new java.awt.Color(153, 255, 204));
        jb6.setForeground(new java.awt.Color(51, 0, 51));
        jb6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        getContentPane().add(jb6);
        jb6.setBounds(228, 79, 23, 18);

        jb7.setBackground(new java.awt.Color(51, 0, 51));
        jb7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb7);
        jb7.setBounds(282, 79, 23, 18);

        jb9.setBackground(new java.awt.Color(51, 0, 51));
        jb9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb9);
        jb9.setBounds(395, 78, 23, 18);

        jb2.setBackground(new java.awt.Color(153, 255, 204));
        jb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jb2);
        jb2.setBounds(283, 36, 23, 18);

        jb8.setBackground(new java.awt.Color(153, 255, 204));
        jb8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        getContentPane().add(jb8);
        jb8.setBounds(336, 79, 23, 18);

        Current_time2.setEditable(false);
        Current_time2.setBackground(new java.awt.Color(204, 204, 204));
        Current_time2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_time2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Current_time2.setToolTipText("Current_Time");
        Current_time2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Current_time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Current_time2ActionPerformed(evt);
            }
        });
        getContentPane().add(Current_time2);
        Current_time2.setBounds(0, 61, 208, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -6, 710, 460);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-6, 450, 720, 320);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 290, 610, 480);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 0, 610, 290);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllDataTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDataTextButtonActionPerformed
        SimpleDateFormat DFormat=new SimpleDateFormat("d/M/y");
        //String date=DFormat.format(Jdate1.getDate());
        //allDate = date;
        int size = allDate.length();
        if (size < 8 || size>10) {
            JOptionPane.showMessageDialog(null, "Plz Entry full Date", "Warning", 2);
            AllDateText.setText("");
        } else {
            AllDateText.setText(allDate);
        }
        String[] ss = allDate.split("/");
        allDate = "" + ss[0] + "/" + ss[1] + "/" + ss[2];
        dd = Integer.parseInt(ss[0]);
        mm = Integer.parseInt(ss[1]);
        yy = Integer.parseInt(ss[2]);
    }//GEN-LAST:event_AllDataTextButtonActionPerformed

    private void AddEventClear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventClear2ActionPerformed
        AddEventFieldEventName.setText("");
    }//GEN-LAST:event_AddEventClear2ActionPerformed

    private void AllDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllDateTextActionPerformed

    private void AddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClearButtonActionPerformed
        AddTextArea.setText("");
    }//GEN-LAST:event_AddClearButtonActionPerformed

    private void AddEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEnterButtonActionPerformed
        EventName1 = AddEventFieldEventName.getText();
        AllDate1 = AllDateText.getText();
        String aaa=EventName1+""+1;
        String aaa1=AllDate1+""+1;
        String aaa2=AddTextArea.getText()+""+1;
        int sss=aaa.length();
        int sss1=aaa1.length();
        int sss2=aaa2.length();        
        if (sss<=1 || sss1<=1 || sss2<=1) {
            JOptionPane.showMessageDialog(null, "Plz Entry full Information", "Warning", 2);
            AddEventFieldEventName.setText("");
            AllDateText.setText("");
            AddTextArea.setText("");
        } else {
            x++;
            //System.out.println(x);
            if (x == 1) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event1.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 2) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event2.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 3) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event3.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 4) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event4.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 5) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event5.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 6) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event6.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 7) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event7.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 8) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event8.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 9) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event9.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            } else if (x == 10) {
                String path = "E:/java/class practiac/Calendars/Info/AddEvent/Event10.txt";

                try {
                    PrintWriter p2 = new PrintWriter(path);
                    String line = AddTextArea.getText();
                    p2.println(line);
                    p2.flush();
                    p2.close();
                } catch (Exception ex) {
                    System.out.println("error = " + ex.getMessage());
                }
            }
            AddEventFieldEventName.setText("");
            AllDateText.setText("");
            AddTextArea.setText("");
            model = (DefaultTableModel) AddEventTabel.getModel();
            model.addRow(new Object[]{x, EventName1, AllDate1});
        }


    }//GEN-LAST:event_AddEnterButtonActionPerformed

    private void AddBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBackButtonActionPerformed
        this.dispose();
        ChooseEvent f = new ChooseEvent();
    }//GEN-LAST:event_AddBackButtonActionPerformed

    private void AddEventTabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddEventTabelMouseClicked
        DefaultTableModel model = (DefaultTableModel) AddEventTabel.getModel();
        int index = AddEventTabel.getSelectedRow();
        ChooseEventFieldname.setText(model.getValueAt(index, 1).toString());
        ChooseEventFieldDate.setText(model.getValueAt(index, 2).toString());
        String st = ChooseEventFieldDate.getText();
        String[] ss = st.split("/");
        allDate = "" + ss[0] + "/" + ss[1] + "/" + ss[2];
        dd = Integer.parseInt(ss[0]);
        mm = Integer.parseInt(ss[1]);
        yy = Integer.parseInt(ss[2]);
    }//GEN-LAST:event_AddEventTabelMouseClicked

    private void ChooseEventEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseEventEnterButtonActionPerformed
        calculationDay();
        DefaultTableModel model = (DefaultTableModel) AddEventTabel.getModel();
        int index = AddEventTabel.getSelectedRow();
        int xt=Integer.parseInt(model.getValueAt(index, 0).toString());
        System.out.println(xt);
        OutputData2 f = new OutputData2(xt, allDate, dateday);
        this.dispose();
    }//GEN-LAST:event_ChooseEventEnterButtonActionPerformed

    private void ChooseExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ChooseExitActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb4ActionPerformed

    private void Current_date2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Current_date2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Current_date2ActionPerformed

    private void jb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb10ActionPerformed

    private void Time_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_dateActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb8ActionPerformed

    private void Current_time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Current_time2ActionPerformed

    }//GEN-LAST:event_Current_time2ActionPerformed

    public void calculationDay() {
        int n, year = yy, month = mm, date = dd, year_valu = 0, month_valu = 0, remnant = 0, div, all_sum, day;

        if ((100 <= year && year < 200) || (800 <= year && year < 900) || (1500 <= year && year < 1600) || (2100 <= year && year < 2200) || (2400 <= year && year < 2900) || (3500 <= year && year < 3600) || (4200 <= year && year < 4300) || (4900 <= year && year < 5000)) {
            if (100 <= year && year < 200) {
                year_valu = 5;
                remnant = year - 100;
            } else if (800 <= year && year < 900) {
                year_valu = 5;
                remnant = year - 800;
            } else if (1500 <= year && year < 1600) {
                year_valu = 5;
                remnant = year - 1500;
            } else if (2100 <= year && year < 2200) {
                year_valu = 5;
                remnant = year - 2100;
            } else if (2400 <= year && year < 2900) {
                year_valu = 5;
                remnant = year - 2400;
            } else if (3500 <= year && year < 3600) {
                year_valu = 5;
                remnant = year - 3500;
            } else if (4200 <= year && year < 4300) {
                remnant = year - 4200;
            } else if (4900 <= year && year < 5000) {
                year_valu = 5;
                remnant = year - 4900;
            }
        } else if ((200 <= year && year < 300) || (900 <= year && year < 1000) || (1600 <= year && year < 1700) || (2200 <= year && year < 2300) || (2900 <= year && year < 3000) || (3600 <= year && year < 3700) || (4300 <= year && year < 4400) || (year == 5000)) {
            if (200 <= year && year < 300) {
                year_valu = 4;
                remnant = year - 200;
            } else if (900 <= year && year < 1000) {
                year_valu = 4;
                remnant = year - 900;
            } else if (1600 <= year && year < 1700) {
                year_valu = 4;
                remnant = year - 1600;
            } else if (2200 <= year && year < 2300) {
                year_valu = 4;
                remnant = year - 2200;
            } else if (2900 <= year && year < 3000) {
                year_valu = 4;
                remnant = year - 2900;
            } else if (3600 <= year && year < 3700) {
                year_valu = 4;
                remnant = year - 3600;
            } else if (4300 <= year && year < 4400) {
                year_valu = 4;
                remnant = year - 4300;
            } else if (year == 5000) {
                year_valu = 4;
                remnant = year - 5000;
            }
        } else if ((300 <= year && year < 400) || (1000 <= year && year < 1100) || (1700 <= year && year < 1800) || (2300 <= year && year < 2400) || (3000 <= year && year < 3100) || (3700 <= year && year < 3800) || (4400 <= year && year < 4500)) {
            if (300 <= year && year < 400) {
                year_valu = 3;
                remnant = year - 300;
            } else if (1000 <= year && year < 1100) {
                year_valu = 3;
                remnant = year - 1000;
            } else if (1700 <= year && year < 1800) {
                year_valu = 3;
                remnant = year - 1700;
            } else if (2300 <= year && year < 2400) {
                year_valu = 3;
                remnant = year - 2300;
            } else if (3000 <= year && year < 3100) {
                year_valu = 3;
                remnant = year - 3000;
            } else if (3700 <= year && year < 3800) {
                year_valu = 3;
                remnant = year - 3700;
            } else if (4400 <= year && year < 4500) {
                year_valu = 3;
                remnant = year - 4400;
            }
        } else if ((400 <= year && year < 500) || (1100 <= year && year < 1200) || (1800 <= year && year < 1900) || (2400 <= year && year < 2500) || (3100 <= year && year < 3200) || (3800 <= year && year < 3900) || (4500 <= year && year < 4600)) {
            if (400 <= year && year < 500) {
                year_valu = 2;
                remnant = year - 400;
            } else if (1100 <= year && year < 1200) {
                year_valu = 2;
                remnant = year - 1100;
            } else if (1800 <= year && year < 1900) {
                year_valu = 2;
                remnant = year - 1800;
            } else if (2400 <= year && year < 2500) {
                year_valu = 2;
                remnant = year - 2400;
            } else if (3100 <= year && year < 3200) {
                year_valu = 2;
                remnant = year - 3100;
            } else if (3800 <= year && year < 3900) {
                year_valu = 2;
                remnant = year - 3800;
            } else if (4500 <= year && year < 4600) {
                year_valu = 2;
                remnant = year - 4500;
            }
        } else if ((500 <= year && year < 600) || (1200 <= year && year < 1300) || (2500 <= year && year < 2600) || (3200 <= year && year < 3300) || (3900 <= year && year < 4000) || (4600 <= year && year < 4700)) {
            if (500 <= year && year < 600) {
                year_valu = 1;
                remnant = year - 500;
            } else if (1200 <= year && year < 1300) {
                year_valu = 1;
                remnant = year - 1200;
            } else if (2500 <= year && year < 2600) {
                year_valu = 1;
                remnant = year - 2500;
            } else if (3200 <= year && year < 3300) {
                year_valu = 1;
                remnant = year - 3200;
            } else if (3900 <= year && year < 4000) {
                year_valu = 1;
                remnant = year - 3900;
            } else if (4600 <= year && year < 4700) {
                year_valu = 1;
                remnant = year - 4600;
            }
        } else if ((600 <= year && year < 700) || (1300 <= year && year < 1400) || (1900 <= year && year < 2000) || (2600 <= year && year < 2700) || (3300 <= year && year < 3400) || (4000 <= year && year < 4100) || (4700 <= year && year < 4800)) {
            if (600 <= year && year < 700) {
                year_valu = 0;
                remnant = year - 600;
            } else if (1300 <= year && year < 1400) {
                year_valu = 0;
                remnant = year - 1300;
            } else if (1900 <= year && year < 2000) {
                year_valu = 0;
                remnant = year - 1900;
            } else if (2600 <= year && year < 2700) {
                year_valu = 0;
                remnant = year - 2600;
            } else if (3300 <= year && year < 3400) {
                year_valu = 0;
                remnant = year - 3300;
            } else if (4000 <= year && year < 4100) {
                year_valu = 0;
                remnant = year - 4000;
            } else if (4700 <= year && year < 4800) {
                year_valu = 0;
                remnant = year - 4700;
            }
        } else if ((700 <= year && year < 800) || (1400 <= year && year < 1500) || (2000 <= year && year < 2100) || (2700 <= year && year < 2800) || (3400 <= year && year < 3500) || (4100 <= year && year < 4200) || (4800 <= year && year < 4900)) {
            if (700 <= year && year < 800) {
                year_valu = 6;
                remnant = year - 700;
            } else if (1400 <= year && year < 1500) {
                year_valu = 6;
                remnant = year - 1400;
            } else if (2000 <= year && year < 2100) {
                year_valu = 6;
                remnant = year - 2000;
            } else if (2700 <= year && year < 2800) {
                year_valu = 6;
                remnant = year - 2700;
            } else if (3400 <= year && year < 3500) {
                year_valu = 6;
                remnant = year - 3400;
            } else if (4100 <= year && year < 4200) {
                year_valu = 6;
                remnant = year - 4100;
            } else if (4800 <= year && year < 4900) {
                year_valu = 6;
                remnant = year - 4800;
            }
        }

        if ((year % 4 == 0 && year % 100 != 0) || (year % 400 == 0)) {
            if (month == 1) {
                month_valu = 0;
            } else if (month == 2) {
                month_valu = 3;
            }
        } else {
            if (month == 1) {
                month_valu = 1;
            } else if (month == 2) {
                month_valu = 4;
            }
        }
        if ((month == 3) || (month == 11)) {
            month_valu = 4;
        } else if ((month == 4) || (month == 7)) {
            month_valu = 0;
        } else if (month == 5) {
            month_valu = 2;
        } else if (month == 6) {
            month_valu = 5;
        } else if (month == 8) {
            month_valu = 3;
        } else if ((month == 9) || (month == 12)) {
            month_valu = 6;
        } else if (month == 10) {
            month_valu = 1;
        }

        div = remnant / 4;

        all_sum = year_valu + remnant + div + month_valu + date;

        day = all_sum % 7;

        if (day == 0) {
            dateday = "Saturday";
        } else if (day == 1) {
            dateday = "Sunday";
        } else if (day == 2) {
            dateday = "Monday";
        } else if (day == 3) {
            dateday = "Tuesday";
        } else if (day == 4) {
            dateday = "Wednesday";
        } else if (day == 5) {
            dateday = "Thursday";
        } else if (day == 6) {
            dateday = "Friday";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEvent f = new AddEvent();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBackButton;
    private javax.swing.JButton AddClearButton;
    private javax.swing.JButton AddEnterButton;
    private javax.swing.JButton AddEventClear2;
    private javax.swing.JTextField AddEventFieldEventName;
    private javax.swing.JLabel AddEventLavel;
    private javax.swing.JTable AddEventTabel;
    private javax.swing.JLabel AddInformationLabel;
    private javax.swing.JTextArea AddTextArea;
    private javax.swing.JButton AllDataTextButton;
    private javax.swing.JTextField AllDateText;
    private javax.swing.JButton ChooseEventEnterButton;
    private javax.swing.JTextField ChooseEventFieldDate;
    private javax.swing.JTextField ChooseEventFieldname;
    private javax.swing.JLabel ChooseEventLabel;
    private javax.swing.JButton ChooseExit;
    private javax.swing.JLabel Current_Date2;
    private javax.swing.JLabel Current_Time2;
    private javax.swing.JTextField Current_date2;
    private javax.swing.JTextField Current_time2;
    private javax.swing.JLabel DataEntryDMY;
    private javax.swing.JLabel INFOLavel;
    private javax.swing.JTextField Time_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb10;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    // End of variables declaration//GEN-END:variables
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     