package Wellcome;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JFrame; 
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
/**
 *
 * @author Kibria
 */
public class ChooseEvent extends javax.swing.JFrame {
    /**
     * Creates new form ChooseEvent
     */
    private Container c;
     private JMenu m1,m2,m3;
    private JMenuBar mm;
    private ImageIcon im;
    private JMenuItem b1,b2,b3,b4,b5;
    public ChooseEvent() {
        initComponents();        
        c = this.getContentPane();
        this.setVisible(true);
        this.setSize(840,570);
        this.setLocation(280,80);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setTitle("Home_Page");
        this.setResizable(false);
        Current_Date_Time ff=new Current_Date_Time();
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("project.jpg")));
        Image im1 = myimage.getImage();
        Image im2 = im1.getScaledInstance(home_pic.getWidth(),home_pic.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon fff=new ImageIcon(im2);
        home_pic.setIcon(fff);
         String Time=ff.Current_Time;
         String Date=ff.Current_Date;
         Current_time.setText(Time);
         Current_date.setText(Date);
        c.setBackground(Color.PINK);
       
        
   
        mm=new JMenuBar();
        this.setJMenuBar(mm);
        //c.add(mm);
        
        m1=new JMenu("About");
        m2=new JMenu("Help");
        mm.add(m1);
        mm.add(m2);
        
        
        b1=new JMenuItem("About Of Developer");
        b2=new JMenuItem("About Of Project");
        b3=new JMenuItem("Exit");
        m1.add(b1);
        m1.add(b2);
        m1.add(b3);        
         b1.addActionListener(new ActionListener() {
               public void actionPerformed(ActionEvent a)
               {
                 About_Developer ff=new About_Developer();
               } 
        });
        b2.addActionListener(new ActionListener() {
               public void actionPerformed(ActionEvent a)
               {
                   About_Project f= new About_Project();
               }            
        });
        b3.addActionListener(new ActionListener() {
               public void actionPerformed(ActionEvent a)
               {
                           System.exit(0);
               }
        });
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        AddEvent = new javax.swing.JButton();
        ChooseDate = new javax.swing.JButton();
        ChooseEvent = new javax.swing.JButton();
        ChossePicPanel = new javax.swing.JPanel();
        PicLebel = new javax.swing.JLabel();
        Current_time = new javax.swing.JTextField();
        Current_date = new javax.swing.JTextField();
        Time_date = new javax.swing.JTextField();
        jb3 = new javax.swing.JButton();
        jb5 = new javax.swing.JButton();
        jb1 = new javax.swing.JButton();
        jb6 = new javax.swing.JButton();
        jb7 = new javax.swing.JButton();
        jb9 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        jb8 = new javax.swing.JButton();
        jb4 = new javax.swing.JButton();
        jb10 = new javax.swing.JButton();
        Current_Date2 = new javax.swing.JLabel();
        Current_Time2 = new javax.swing.JLabel();
        home_pic = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AddEvent.setBackground(new java.awt.Color(51, 0, 51));
        AddEvent.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        AddEvent.setForeground(new java.awt.Color(204, 204, 0));
        AddEvent.setText("AddEvent");
        AddEvent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 2, true));
        AddEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventActionPerformed(evt);
            }
        });
        getContentPane().add(AddEvent);
        AddEvent.setBounds(39, 446, 190, 49);

        ChooseDate.setBackground(new java.awt.Color(51, 0, 51));
        ChooseDate.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseDate.setForeground(new java.awt.Color(204, 204, 0));
        ChooseDate.setText("ChooseDate");
        ChooseDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 2));
        ChooseDate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseDateActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseDate);
        ChooseDate.setBounds(328, 446, 190, 49);

        ChooseEvent.setBackground(new java.awt.Color(51, 0, 51));
        ChooseEvent.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        ChooseEvent.setForeground(new java.awt.Color(204, 204, 0));
        ChooseEvent.setText("ChooseEvent");
        ChooseEvent.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 2, true));
        ChooseEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ChooseEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseEventActionPerformed(evt);
            }
        });
        getContentPane().add(ChooseEvent);
        ChooseEvent.setBounds(606, 446, 190, 49);

        ChossePicPanel.setBackground(new java.awt.Color(204, 255, 255));

        PicLebel.setToolTipText("");
        PicLebel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PicLebel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout ChossePicPanelLayout = new javax.swing.GroupLayout(ChossePicPanel);
        ChossePicPanel.setLayout(ChossePicPanelLayout);
        ChossePicPanelLayout.setHorizontalGroup(
            ChossePicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicLebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ChossePicPanelLayout.setVerticalGroup(
            ChossePicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PicLebel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(ChossePicPanel);
        ChossePicPanel.setBounds(815, 11, 4, 4);

        Current_time.setEditable(false);
        Current_time.setBackground(new java.awt.Color(204, 204, 204));
        Current_time.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_time.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Current_time.setToolTipText("Current_Time");
        Current_time.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Current_time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Current_timeActionPerformed(evt);
            }
        });
        getContentPane().add(Current_time);
        Current_time.setBounds(27, 63, 208, 48);

        Current_date.setEditable(false);
        Current_date.setBackground(new java.awt.Color(204, 204, 204));
        Current_date.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_date.setForeground(new java.awt.Color(51, 51, 51));
        Current_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Current_date.setToolTipText("Current_Date");
        Current_date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Current_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Current_dateActionPerformed(evt);
            }
        });
        getContentPane().add(Current_date);
        Current_date.setBounds(587, 63, 207, 49);

        Time_date.setEditable(false);
        Time_date.setBackground(new java.awt.Color(204, 102, 0));
        Time_date.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        Time_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Time_date.setToolTipText("");
        Time_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        Time_date.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Time_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_dateActionPerformed(evt);
            }
        });
        getContentPane().add(Time_date);
        Time_date.setBounds(274, 63, 295, 11);

        jb3.setBackground(new java.awt.Color(51, 0, 51));
        jb3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb3);
        jb3.setBounds(420, 38, 23, 19);

        jb5.setBackground(new java.awt.Color(51, 0, 51));
        jb5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb5);
        jb5.setBounds(526, 38, 23, 18);

        jb1.setBackground(new java.awt.Color(51, 0, 51));
        jb1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb1);
        jb1.setBounds(300, 38, 23, 18);

        jb6.setBackground(new java.awt.Color(153, 255, 204));
        jb6.setForeground(new java.awt.Color(51, 0, 51));
        jb6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb6ActionPerformed(evt);
            }
        });
        getContentPane().add(jb6);
        jb6.setBounds(304, 81, 23, 18);

        jb7.setBackground(new java.awt.Color(51, 0, 51));
        jb7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb7);
        jb7.setBounds(363, 81, 23, 18);

        jb9.setBackground(new java.awt.Color(51, 0, 51));
        jb9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jb9);
        jb9.setBounds(483, 81, 23, 18);

        jb2.setBackground(new java.awt.Color(153, 255, 204));
        jb2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });
        getContentPane().add(jb2);
        jb2.setBounds(361, 38, 23, 18);

        jb8.setBackground(new java.awt.Color(153, 255, 204));
        jb8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb8ActionPerformed(evt);
            }
        });
        getContentPane().add(jb8);
        jb8.setBounds(423, 81, 23, 18);

        jb4.setBackground(new java.awt.Color(153, 255, 204));
        jb4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jb4);
        jb4.setBounds(478, 38, 23, 18);

        jb10.setBackground(new java.awt.Color(153, 255, 204));
        jb10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 3, true));
        jb10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb10ActionPerformed(evt);
            }
        });
        getContentPane().add(jb10);
        jb10.setBounds(530, 81, 23, 18);

        Current_Date2.setBackground(new java.awt.Color(204, 204, 204));
        Current_Date2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_Date2.setForeground(new java.awt.Color(0, 51, 51));
        Current_Date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Current_Date2.setText("Current_Date");
        Current_Date2.setToolTipText("Current_Date");
        Current_Date2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        getContentPane().add(Current_Date2);
        Current_Date2.setBounds(589, 11, 205, 45);

        Current_Time2.setBackground(new java.awt.Color(204, 204, 204));
        Current_Time2.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        Current_Time2.setForeground(new java.awt.Color(0, 51, 51));
        Current_Time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Current_Time2.setText("Current_Time");
        Current_Time2.setToolTipText("Current_Time");
        Current_Time2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        getContentPane().add(Current_Time2);
        Current_Time2.setBounds(27, 12, 208, 45);

        home_pic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51), new java.awt.Color(51, 0, 51)));
        getContentPane().add(home_pic);
        home_pic.setBounds(20, 130, 787, 283);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek3.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 840, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseDateActionPerformed
        this.dispose();
        DataEntry f = new DataEntry();
    }//GEN-LAST:event_ChooseDateActionPerformed

    private void ChooseEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseEventActionPerformed
         this.dispose();
        ChooseEventFrame f= new ChooseEventFrame();
    }//GEN-LAST:event_ChooseEventActionPerformed

    private void AddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventActionPerformed
        this.dispose();
        AddEvent f= new AddEvent();
    }//GEN-LAST:event_AddEventActionPerformed

    private void Current_timeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Current_timeActionPerformed
        

    }//GEN-LAST:event_Current_timeActionPerformed

    private void Current_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Current_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Current_dateActionPerformed

    private void Time_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_dateActionPerformed

    private void jb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb6ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb2ActionPerformed

    private void jb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb8ActionPerformed

    private void jb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb4ActionPerformed

    private void jb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChooseEvent f=new ChooseEvent();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEvent;
    private javax.swing.JButton ChooseDate;
    private javax.swing.JButton ChooseEvent;
    private javax.swing.JPanel ChossePicPanel;
    private javax.swing.JLabel Current_Date2;
    private javax.swing.JLabel Current_Time2;
    private javax.swing.JTextField Current_date;
    private javax.swing.JTextField Current_time;
    private javax.swing.JLabel PicLebel;
    private javax.swing.JTextField Time_date;
    private javax.swing.JLabel home_pic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb10;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JButton jb4;
    private javax.swing.JButton jb5;
    private javax.swing.JButton jb6;
    private javax.swing.JButton jb7;
    private javax.swing.JButton jb8;
    private javax.swing.JButton jb9;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    // End of variables declaration//GEN-END:variables
}
