/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Wellcome;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Kibria
 */
public class Wellcome extends javax.swing.JFrame {

    /**
     * Creates new form Wellcome
     */
    private Container c;

    public Wellcome() {
        initComponents();
        c = this.getContentPane();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setBounds(400, 190, 475, 298);
        this.setTitle("Smart_Calender");
        c.setBackground(Color.PINK);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WellcomeLebel = new javax.swing.JLabel();
        OpenButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        getContentPane().setLayout(null);

        WellcomeLebel.setBackground(new java.awt.Color(51, 255, 0));
        WellcomeLebel.setFont(new java.awt.Font("Georgia Pro Black", 3, 36)); // NOI18N
        WellcomeLebel.setForeground(new java.awt.Color(102, 0, 102));
        WellcomeLebel.setText("     WELLCOME");
        getContentPane().add(WellcomeLebel);
        WellcomeLebel.setBounds(64, 24, 334, 66);

        OpenButton.setBackground(new java.awt.Color(51, 0, 51));
        OpenButton.setFont(new java.awt.Font("PMingLiU-ExtB", 3, 24)); // NOI18N
        OpenButton.setForeground(new java.awt.Color(153, 153, 0));
        OpenButton.setText("Open");
        OpenButton.setToolTipText("Open");
        OpenButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 51), 3, true));
        OpenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OpenButton);
        OpenButton.setBounds(150, 140, 156, 66);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Wellcome/bek.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenButtonActionPerformed
        this.dispose();
        new ChooseEvent();
        
    }//GEN-LAST:event_OpenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wellcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wellcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wellcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wellcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Wellcome f = new Wellcome();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenButton;
    private javax.swing.JLabel WellcomeLebel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
